// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYfIUH1VAAX2JEa83IhwPR-ENnl9HZiwk',
    appId: '1:1010864606484:android:381f759011288495b40601',
    messagingSenderId: '1010864606484',
    projectId: 'exptrck-69969',
    storageBucket: 'exptrck-69969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0kjIumdwZgqzJNxwMcQmQvF4-VQ22hk',
    appId: '1:1010864606484:ios:53787feda4e75eb4b40601',
    messagingSenderId: '1010864606484',
    projectId: 'exptrck-69969',
    storageBucket: 'exptrck-69969.firebasestorage.app',
    iosBundleId: 'com.example.expTrck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0kjIumdwZgqzJNxwMcQmQvF4-VQ22hk',
    appId: '1:1010864606484:ios:53787feda4e75eb4b40601',
    messagingSenderId: '1010864606484',
    projectId: 'exptrck-69969',
    storageBucket: 'exptrck-69969.firebasestorage.app',
    iosBundleId: 'com.example.expTrck',
  );
}
